### ISSUE TITLE
Rstudio unresponsive

### ISSUE THREAD

**Issue by caitlinkroeger** [2i2c-org/farallon-image#25]
I've been trying to access RStudio from the JupyterLab launcher and it opens to projects I've been working on, but I can't click on anything and eventually get a notice that it is unresponsive. This also freezes up the JupiterLab and I have to close out the window and open it back up to shut down the server. Nothing else in Chrome or my computer is unresponsive while this is occuring. Any help much appreciated, thanks!

**Comment by yuvipanda** [comment]
Thanks for opening the issue, @caitlinkroeger! Not sure what's happening with JupyterLab there :( There's a new major version out, hopefull that'll help?

In the meantime, you can open RStudio directly from farallon.2i2c.cloud/hub/user-redirect/rstudio. LMK if that works?

**Comment by caitlinkroeger** [comment]
Thanks for the quick response @yuvipanda - still no luck. I was running a model the last time RStudio was working and got knocked off the server, possibly before it finished, so I wonder if RStudio is trying to load the RData file and stuck somehow because maybe there isn't enough memory?

**Comment by yuvipanda** [comment]
@caitlinkroeger ah, that's very useful information! I've cleared out your RStudio session (Moved it from `.rstudio` to `.rstudio.bak`) and RStudio seems to be loading fine. Can you check?

On Firefox, I got a popup saying 'This page is slowing your browser down. | Stop it | Wait'. So it was also a browser freeze, rather than anything on the server. Chrome is smarter and doesn't let it affect other browser tabs. So I suspect some kinda visualization / data display in the client is causing the issue. 

Can you try again and let me know how it works? If you want to reset your session, you can open a terminal in JupyterLab and run `rm -rf .rstudio` or `mv .rstudio .rstudio.bak.<date>`. We'll hopefully have an UI to do this soon.

**Comment by caitlinkroeger** [comment]
It works, thank you!! And thanks for the instruction on how to fix it if this happens again.
